@api_url = http://localhost:2405/v1/api

###

POST {{api_url}}/product/createProduct
Content-Type: application/json
x-api-key: 7fc10a33b6375d1a1eb03a4d50118e9db9c1d42b54735c035975dff0a11d83ad5ef08fa7ad42caaf4830d1aa2b5ecd3f5b7394fbbf2d4731b043ab58507aa895
x-client-id: 66329bd1f629172f022297ab
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjMyOWJkMWY2MjkxNzJmMDIyMjk3YWIiLCJlbWFpbCI6Im5rZXlza3VvMTI0QGdtYWlsLmNvbSIsImlhdCI6MTcxNTE3ODQxNSwiZXhwIjoxNzE1MzUxMjE1fQ.8gFf48WQDrV4A9AZA1HcWOhLS-MIo_2nzLejgOjzAGY

 {
    "productName": "Sofa nằm",
    "thumbnail": "https://cloudinary.com/...",
    "desc": "Sản phẩm nhập khầu từ hàn quốc với nhiều mẫu mã",
    "price": 2500000,
    "productType": "Furniture",
    "shop": "66329bd1f629172f022297ab",
    "attributes": {
        "brand": "Vua",
        "origin": "Trung quốc",
        "expiry": 3
    }
}


### 

GET {{api_url}}/product/findAllDraftsForShop
Content-Type: application/json
x-api-key: 7fc10a33b6375d1a1eb03a4d50118e9db9c1d42b54735c035975dff0a11d83ad5ef08fa7ad42caaf4830d1aa2b5ecd3f5b7394fbbf2d4731b043ab58507aa895
x-client-id: 66329bd1f629172f022297ab
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjMyOWJkMWY2MjkxNzJmMDIyMjk3YWIiLCJlbWFpbCI6Im5rZXlza3VvMTI0QGdtYWlsLmNvbSIsImlhdCI6MTcxNTE3ODQxNSwiZXhwIjoxNzE1MzUxMjE1fQ.8gFf48WQDrV4A9AZA1HcWOhLS-MIo_2nzLejgOjzAGY