@api_url = http://localhost:2405/v1/api
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ0YjE1OTMzNDI2NWQ4MzljNTUyYjAiLCJlbWFpbCI6Im5rZXlza3VvMTI0N0BnbWFpbC5jb20iLCJpYXQiOjE3MTU3NzgyMDEsImV4cCI6MTcxNTk1MTAwMX0.y6tHm2AllPXphohRCejzQ_KtWggr0YT_dFm1GZ7NNTA
@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQ0YjE1OTMzNDI2NWQ4MzljNTUyYjAiLCJlbWFpbCI6Im5rZXlza3VvMTI0N0BnbWFpbC5jb20iLCJpYXQiOjE3MTU3NzgyMDEsImV4cCI6MTcxNjM4MzAwMX0.g96jdk6fIXUkcCr9kCJTKvexNni9qlAxBv8qDSKFS6k
@api_key = 688014e63f23f0d1d00779fb5a713376d3d53cbcb59bb787ad04922f86bea87ace437da70313101eba1e8a8e828e80ec99546d1bf9668a7979115a29b6ad62db

###

POST {{api_url}}/user/register
Content-Type: application/json 

{
    "fullname": "Kuo Nhan Dung",
    "email": "nkeyskuo1247@gmail.com",
    "password": "9952811",
    "phone": "0767916592"
}

###

POST {{api_url}}/user/login
Content-Type: application/json
x-api-key: {{api_key}}

{
    "email": "nkeyskuo1247@gmail.com",
    "password": "9952811"
}

###

POST {{api_url}}/user/logout
Content-Type: application/json
x-api-key: {{api_key}}
x-client-id: 6644b159334265d839c552b0
Authorization: {{access_token}}


###

POST {{api_url}}/user/refreshTokenPair
Content-Type: application/json
x-api-key: {{api_key}}
x-client-id: 6644b159334265d839c552b0
Authorization: {{access_token}}
x-rtoken-id: {{refresh_token}}
